### ISSUE TITLE
¿Funciona con aidoo?

### ISSUE THREAD

**Issue by fogoner** [fjhorrillo/homebridge-airzone-cloud#12]
**Describe Your Problem:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by fjhorrillo** [comment]
Hola,

Si con el Aidoo puedes gestionarlo desde www.airzonecloud.com si debería funcionar o podría adaptar lo que fuera necesario para soportarlo, aunque necesitaría poder hacer algunas pruebas con tu ayuda, si quieres puedes pasa por discord y lo comentamos.

Un saludo.

**Comment by fogoner** [comment]
Buenas
Me encantaría ayudarte en las pruebas que necesites, dime en que horarios e intentaré conectarme.
No uso mucho Discord pero mi usuario es ixus#8991

 Un saludo

**Comment by fjhorrillo** [comment]
Usa este enlace para unirte al servidor https://discord.gg/F7pQJEpaHH
