### ISSUE TITLE
no actualiza modo / target temp. 

### ISSUE THREAD

**Issue by dimovic69** [fjhorrillo/homebridge-airzone-cloud#22]
Hola,

Tengo el plugin funcionando correctamente contra mi cuenta DKN Cloud. Pero tengo una duda:
Desde la app Casa pueda dar ordenes al sistema Daikin (cambiar modo frio/calor y poner target temperature) pero sin embargo la app Casa no actualiza la información si es cambiada desde la app DKN o desde el propio control de Daikin. Es decir, parece que el comportamiento es siempre unidireccional (Homebridge > DNK Server), no reflejando el estado correcto si ha recibido ordenes desde otro sitio que no sea el plugin de homebridge. ¿Es correcto este funcionamiento o se trata de un bug?
Sería deseable que el plugin actualizase la info mostrada en la app Casa (modo y target temp.) incluso cuando se ha modificado desde cualquier otro control, la app DKN Cloud así lo hace.

Un saludo

**Comment by fjhorrillo** [comment]
Hola, en principio si se debe actualizar, diría que el problema es que en el caso de tu instalación, la información que se obtiene no tiene el mismo formato que con la que hice las pruebas.
Por favor envíame por aquí o por discord las trazas poniendo el modo debug para así poder ver la información que recibe el plug-in cuando. Haces el cambio desde otro sitio.

**Comment by dimovic69** [comment]
Hola,

Activo modo Debug en el plugin, reinicio, pero no aparece realmente más detalle de registro (tengo que hacer algo mas?)
No tengo claro si actualiza la info con algún evento (peticion de la app Casa) o periodicamente. Lo cierto es que a veces la actualiza pero generalmente no.
Siempre reinicio homebridge sí que toma la info actualizada (lo veo en el log).
Por otra parte, a la app Casa tb le cuesta actuaizar la info, a veces es necesario cerrarla y volverla a abrir (esto ya supongo que no es cosa del plugin...)
Alguna sugerencia??

Saludos

**Comment by fjhorrillo** [comment]
Hola, necesitaría saber si está conectando el wevsockets que es por donde llegan los eventos que genera otro dispositivo, esto debería salir si pone el de uf del plug-in, no el de homebridge.

**Comment by dimovic69** [comment]
Como he comentado, activo modo Debug en el Plugin (opcion dentro de Advanced en la config del plugin), reinicio y aparecen más detalles en el log:

[08/06/2022, 22:27:53] [Aire Acondicionado] Aire Acondicionado: Get Characteristic TemperatureDisplayUnits -> 0 (ºC)
[08/06/2022, 22:27:54] [Aire Acondicionado] Aire Acondicionado: Get Characteristic TargetHeatingCoolingState -> 0 ([1]cool: Cooling mode)
[08/06/2022, 22:27:54] [Aire Acondicionado] Aire Acondicionado: Get Characteristic CurrentHeatingCoolingState -> 2 ([1]cool: Cooling mode)
[08/06/2022, 22:27:54] [Aire Acondicionado] Aire Acondicionado: Get Characteristic TargetTemperature -> 24ºC
[08/06/2022, 22:27:54] [Aire Acondicionado] Aire Acondicionado: Get Characteristic CurrentTemperature -> 27ºC

Nada sobre la conexion websocket de supongo mantendrás con DKN Cloud

Saludos

**Comment by fjhorrillo** [comment]
Ok, estás usando DKN y no AirzoneCloud, por lo que supongo tu api sigue siendo la antigua y no soporta la conexión por websocket.
En ese caso como está implementado es que cada vez que abres la aplicación casa o accedes dentro a un termostato está le pide al plug-in los datos de ese momento, pero no hay una actualización de datos si la aplicación casa no lo solicita.

**Comment by dimovic69** [comment]
Entendido...
Lo que veo es que no siempre que abro Casa  o accedo al termostato se produce la actualización. No tengo claro si es  porque Casa no lo pide (quizas lo tiene cacheado o algo asi) o porque el plugin no lo procesa. 
Se te ocurre como puedo monitorizar estos eventos?

Gracias

**Comment by dimovic69** [comment]
Incluso cuando ordeno desde casa cambio de temp o de modo no actualiza la info (la que fue actualizada desde otro control)

**Comment by fjhorrillo** [comment]
Deberías ver en el log una traza con el get cada vez que la app casa le pide los datos (si está en debug)

**Comment by fjhorrillo** [comment]
Hola, podrías probar con la ultima version (v0.3.4) y si sigue sucediendo habilitar el debug y compartirme los logs, por aquí o por discord, gracias.

**Comment by dimovic69** [comment]
Hola,

He actualizado a 0.3.4 y sigue sucediendo. 

El log indica que lee la temperatura objetivo a 22º (p. Ejemplo) y en realidad la he cambiado de 22º a 16º
También ocurre con el valor de la temperatura ambiente, la he cambiado echando aliento al sensor y se ha elevado a 30º pero sigue recogiendo el valor anterior 23º
También ocurre con el estado. Si está encendido y lo apago en el mando Daikin la App Casa no actualiza el estado a Desactivado, y a la inversa igual.

En general, la lectura de los parametros que hace el plugin sobre el servidor DKN no es correcta. En sentido inverso siempre funciona, cualquier parámetro cambiado desde Casa se refleja correctamente en el sistema Daikin.

Las pruebas la hago cerrando y abriendo la App Casa, y cuando la abro veo en el log que se hacen peticiones pero los parámetros que se muestran son falsos (aparece que los valores los saca de alguna cache, no son los actuales)

La app DKN Cloud lee todos los parámetros siempre bien.

Otra cosa, activando el parámetro Debug del plugin no veo que registre más detalles en el log…

Cualquier prueba que te sea de ayuda me la pides. Tengo mucho interés en que esto funcione correctamente.
Gracias por tu ayuda.

Un saludo,

	David

**Comment by fjhorrillo** [comment]
Ok, por un lado error mío ya que en la versión 0.3.4 solo hice correcciones sobre new AirzoneCloud y no sobre DKN que es lo que usas. Voy a revisar si puedo hacer algo, en cuanto a los log, no muestra el de if hasta que reiniciar homebridge.

**Comment by dimovic69** [comment]
Siempre reinicio homebridge después de cambiar la config de cualquier plugin. Ahora me doy cuenta que efectivamente sí se loggea más info, lo que pasa es que yo esperaba algo más detallado como el dialogo con el DKN server… pero no.
Si pudieras arreglarlo para DKN te estaría muy agradecido. De nuevo, me ofrezco para cualquier prueba que quieras hacer.

Saludos

**Comment by dimovic69** [comment]
Hola!
Tienes previsto corregir la parte DKN?

Saludos

**Comment by fjhorrillo** [comment]
Hola, si dame algo de tiempo porque aún no tengo claro cómo hacerlo.

**Comment by dimovic69** [comment]
Si la conexión con el servidor DNK (sistema antiguo) no usa websockets bastaría con hacer polling cada 15 o 30 segundos. Supongo que eso es lo que hace la App DKN Cloud

**Comment by fjhorrillo** [comment]
Implemented in version 0.5.2

**Comment by dimovic69** [comment]
Hola! Gracias por acordarte. Siento decir que ahora la comunicación plugin -> DKN no funciona bien. Falla tanto los cambios de estado (cool, heat, none) como los cambios de target temperature. Generalmente es posible encender en heat o cool pero no funciona cambiar de modo ni apagar.
Si puedo ayudarte con pruebas puedes contar conmigo.

**Comment by dimovic69** [comment]
Acabo de probar la versión 0.5.1 y en esta sí que funciona correctamente la comunicación plugin -> DKN, pero obviamente falla la lectura de DKN -> plugin, es decir, si se altera en el propio mando Daikin el modo o la target temp no se refleja (motivo de apertura de este issue)

**Comment by fjhorrillo** [comment]
Puedes probar la 0.5.2, en esta metí un refresco cada 10 segundos para leer los datos por si cambia dese el mando.

**Comment by dimovic69** [comment]
Hola!

Ayer probé ambas versiones 0.5.2 y 0.5.1. Deje los comentarios en el hilo de Github. Te resumo...

Sobre la 0.5.2: 
- Los cambios en DKN no siempre se reflejan en el plugin (o sea en la App Casa). Ya veo que has implementado un polling de 10 segundos, pero no está funcionando correctamente.
- Por otro lado, ha tenido el efecto colateral de empeorar la comunicación plugin -> DKN, es decir, cuando se hacen cambios en la App Casa en muchas de las ocasiones no llegan a DKN

Probé instalar la versión 0.5.1 para confirmar simplemente que la comunicación plugin -> es correcta (los cambios en la App Casa se reflejan enseguida en DKN) aunque tiene el problemilla por el cual se abrío el issue: No actualiza los cambios realizados desde el mando.

Espero haber sido de ayuda. Un saludo.
