### ISSUE TITLE
Controlar velocidad del ventilador

### ISSUE THREAD

**Issue by BertoTavira** [fjhorrillo/homebridge-airzone-cloud#23]
Buenas :)

Estaría genial poder controlar la velocidad del ventilador del AC. Creo haber visto que con dispositivos tipo Tadoo o Aidoo se puede desde HK.

Habría alguna manera de implementarlo?

Gracias por el curro!

**Comment by fjhorrillo** [comment]
Hola, añadí el on/off para el modo ventilador como un switch no se como se puede gestionar la velocidad aun. Prueba la version 0.5.0
