### ISSUE TITLE
Can't get updated temperature of zone when it's set to off

### ISSUE THREAD

**Issue by matnoublanche** [fjhorrillo/homebridge-airzone-cloud#3]
Hello,

I don't know if it's the expected behavior but when I set a zone to off position, temperature and humidity can't update.

On the Airzone app temperature are always up-to-date.

Mathieu.

**Comment by fjhorrillo** [comment]
Hello, I will check, but you are right, the expected behaviour is to show the current temperature and humidity.

**Comment by fjhorrillo** [comment]
Fixed in version 0.1.1
