### ISSUE TITLE
Missing  only "ventilation mode" wihtout heating or cooling

### ISSUE THREAD

**Issue by Reeon89** [fjhorrillo/homebridge-airzone-cloud#30]
I miss in the HomeKit app the ventilation mode without heating or cooling. I got a AC unit with fresh air from outside and i want to use it as a ventilation system sometimes. Can you add this?

btw: thanks for the project!

**Comment by simonetolomelli** [comment]
+1

**Comment by fjhorrillo** [comment]
Done in version 0.5.0
