### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by bertrandg31** [fjhorrillo/homebridge-airzone-cloud#41]
**Describe Your Problem:**
i cant use the plug in

**Logs:**

Airzone Cloud Bridge starting
01/12/2023, 14:01:52Airzone Cloud BridgeLoaded plugin 'homebridge-airzone-cloud'
01/12/2023, 14:01:52Airzone Cloud BridgeLoading 1 platforms...
01/12/2023, 14:01:52Airzone Cloud BridgeAirzoneCloudDebug mode on: true
01/12/2023, 14:01:52Airzone Cloud BridgeAirzoneCloudERRORMissing auto_off in Config.
01/12/2023, 14:01:52Airzone Cloud BridgeAirzoneCloudERRORInvalid config.json: {"platform":"AirzoneCloud","name":"AirzoneCloud","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15","system":"https://dkn.airzonecloud.com","login":{"email":"bertrand@bgd31.fr","password":"*************"},"debug":true}
01/12/2023, 14:01:52Airzone Cloud BridgeBridge is running on port 51856.
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by fjhorrillo** [comment]
Hi, please edit an save the configuration to set the missing config value.

**Comment by bertrandg31** [comment]
Hello, thank you for your help.

    "platform": "AirzoneCloud",
    "name": "AirzoneCloud",
   "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15",
    "system": "https://www.airzonecloud.com",
    "login": {
        "email": "bertrand@bgd31.fr",
        "password": "XXXXXXXXX"
    },
    "debug": true
}

**Comment by fjhorrillo** [comment]
Hello, in your config is missing the "auto_off", Adding it will work again.

```
{
    "auto_off": true,
    "debug": true,
    "login": {
        "email": "mail@server.com",
        "password": "********************"
    },
    "name": "AirzoneCloud",
    "platform": "AirzoneCloud",
    "system": "https://m.airzonecloud.com",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15"
}
```

**Comment by bertrandg31** [comment]
Hello, 
Thank you very much…
It Works….!!!!


Bien à vous, 

Bertrand Guenoun
11 Bis Rue Montplaisir
31 320 Vieille-Toulouse
06 79 43 37 81.
***@***.***

**Comment by bertrandg31** [comment]
Thank you very much for your help, the installation on Homebridge went well, however when I want to add the bridge to the Home app, the app tells me that this bridge is already added on another Home. Do you know why? Thank you

**Comment by fjhorrillo** [comment]
If you already added the homebridge to your home you don’t need to do it again, automatically the thermostat will show.
