### ISSUE TITLE
Bloqueo plugin Airzone cada 48 horas

### ISSUE THREAD

**Issue by druizben** [fjhorrillo/homebridge-airzone-cloud#49]
**Describe The Bug:**
Tengo un sistema Airzone con multiples dispositivos que forman el sistema de Aerotermia. Tengo termostatos Airzone en las habitaciones, varias maquinas fan coils (impulsores de aire) y una maquina AC independiente. Todos los equipos están correctamente registrados en Airzone Cloud. La integración con HomeKit es a través de un dispositivo HOOBS e inicialmente todo se integra correctamente y los sistemas se muestran en la App Casa

Hay dos dispositivos que generan continuamente errores, cada pocos minutos, relacionados con la lectura del parámetro de Temperatura:

- Airzone HoobsERROR[Airzone Hoobs 8A82@Fan Coils@@Target Temperature] Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'celsius')

Este error provoca que en la App Casa el dispositivo se muestra como "Sin respuesta" aunque lo puedes manejar sin problema...cosa rara.

El mayor de los problemas es que cada 48h todos los dispositivos Airzone se desconectan y ya no es posible manejarlos, sin embargo el bridge está operativo. La única forma que tengo de reactivarlo es reiniciándolo el bridge que contiene el plugin Airzone. Después del crash, se repiten siempre los mismos errores para todos los dispositivos:

- 28/10/2024, 19:30:14Airzone HoobsERROR[Airzone Hoobs 8A82@Current Temperature] The read handler for the characteristic 'Current Temperature' on the accessory 'Alberto' didn't respond at all!. Please check that you properly call the callback!
- 28/10/2024, 19:30:14Airzone HoobsERROR[Airzone Hoobs 8A82@Current Temperature] The read handler for the characteristic 'Current Temperature' on the accessory 'Lucia' didn't respond at all!. Please check that you properly call the callback!
- 8/10/2024, 19:30:14Airzone HoobsERROR[Airzone Hoobs 8A82@Current Temperature] The read handler for the characteristic 'Current Temperature' on the accessory 'AC Buardila' didn't respond at all!. Please check that you properly call the callback!

En modo DEBUG consigo ver alguna cosa más, cuando se produce el crash, siempre hay una desconexión con la plataforma:

- 3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [ ERROR ] [Websocket] Socket connect error "notAuthorized"
- 3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [ ERROR ] [Websocket] Disconnect due to red disconnection
- 3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [Websocket] Disconnect socket requested [33m[object Object][0m
- 3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [ DEBUG ] [Websocket] Disconnect: "io client disconnect"

**To Reproduce:**
Inicialmente no tenia claro que seguía un patron de 48h, pero tras multiples observaciones y pruebas, es algo fijo, cada 48h hay una desconexión con la plataforma. La secuencia de mensajes del LOG siempre es la misma. En la Aplicación Casa, aparecen todos los dispositivos "sin respuesta".

**Expected behavior:**

**Logs:**
3/12/2024, 12:32:49 Airzone Hoobs AirzoneCloud [ DEBUG ] [Websocket] authenticate event, replied with a valid token
3/12/2024, 12:33:33 Airzone Hoobs AirzoneCloud [ DEBUG ] [Websocket] ⬇ [33m["DEVICES_UPDATES.28:CC:FF:80:B0:B6.3a1b0c800a879e58ef6fdf20",{"device_id":"3a1b0c800a879e58ef6fdf20","ws_id":"28:CC:FF:80:B0:B6","change":{"status":{"humidity":62,"local_temp":{"celsius":19.3,"fah":67},"zone_work_temp":{"celsius":19.3,"fah":67}},"adv_conf":{"local_temp":{"celsius":19.3,"fah":67}}},"installation_id":"623c70f4926f3533c7559f16"}][0m
3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [ DEBUG ] [Websocket] ⬇ [33m["auth","authenticate"][0m
3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [ DEBUG ] [Websocket] ⬆ [33m["eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJrQUJyS1NxVUdyVENHWkt1dkhjUW8yaXIxakF6MG82RyIsInRva2VuSWQiOiI2NzhiMDdlNS1iZTkzLTQ2ZDYtYjk4My1iNjlhZDg1OGZjY2YiLCJzY29wZXMiOnsiYXoiOiI2MjNjNGYwNTFiNjBhZWIyMTEzMThjMGUifSwianRpIjoiNjAxMmY1NTgtNDI5Ny00NWNlLThlZjYtZjI4ZWI5MmJmZGFkIiwiaWF0IjoxNzMzMDUyODA4LCJleHAiOjE3MzMyMjU2MDh9.fgKiIIcsPHLZH_Z-pMRdamcaGpha_sHyN6VXIh7_Gug"][0m
3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [ DEBUG ] [Websocket] authenticate event, replied with a valid token
3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [ DEBUG ] [Websocket] ⬇ [33m["error","notAuthorized"][0m
3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [ ERROR ] [Websocket] Socket connect error "notAuthorized"
3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [ ERROR ] [Websocket] Disconnect due to red disconnection
3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [Websocket] Disconnect socket requested [33m[object Object][0m
3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [ DEBUG ] [Websocket] Disconnect: "io client disconnect"
3/12/2024, 12:33:49 Airzone Hoobs AirzoneCloud [ ERROR ] [Websocket] Disconnect due to red disconnection

**Plugin Config:**
{
    "name": "AirzoneCloud",
    "system": "https://m.airzonecloud.com",
    "login": {
        "email": "xxx@xxx.com",
        "password": "jajaja"
    },
    "debug": {
        "general": false,
        "time": false,
        "sets": true,
        "gets": false,
        "fetch": false,
        "websocket": false,
        "status": false
    },
    "auto_off": true,
    "cache": {
        "max": 1000,
        "ttl": 10000
    },
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15",
    "custom_base_url": "https://m.airzonecloud.com"
}
**Screenshots:**

**Environment:**

* **Plugin Version**: 0.5.2
* **Homebridge Version**: 1.8.4
* **Node.js Version**: 20.5.1
* **NPM Version**: 
* **Operating System**: Hoobs  HSLF-2. Version SO HOOBS 5.1.8

**Comment by fjhorrillo** [comment]
Hola @druizben, muchas gracias por el análisis, estaba tratando de identificarlo y también creía que era aleatorio pero no encontraba la causa. Voy a ver si puedo manejar ese error para reconectar.

**Comment by fjhorrillo** [comment]
Hola @druizben, subí una nueva versión v0.5.3 que diría corrige el problema ya que cambiaron el texto del evento 401 por notAuthorized, lo añado en la lógica de reconexión y debería resolverlo, lo veremos en dos días ^^

**Comment by druizben** [comment]
Buenas de nuevo Francisco! llevo un par de semanas esperando la version 0.5.3 pero veo que en el repositorio de plugins no se actualiza, el repositorio fuente para HOOBS es GitHub.com. Te muestro alguna captura de lo que indica el HOOBS, no se si falta incluir el plugin en alguna otra parte, ya te digo que desde HOOBS no se ve...

![WhatsApp Image 2024-12-28 at 18 00 49](https://github.com/user-attachments/assets/61bae736-a39b-4ac8-8c52-b6a4965ab02f)

![WhatsApp Image 2024-12-28 at 18 00 49 (1)](https://github.com/user-attachments/assets/a8c96ceb-4e6e-4dd7-b319-271725519c19)

**Comment by fjhorrillo** [comment]
Fixed correctly in version 0.5.4
