### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by Pascal26120** [fjhorrillo/homebridge-airzone-cloud#6]
Hi,
Do you have a config.json sample  for this plugins ?
Regards

**Comment by fjhorrillo** [comment]
Hello, why do you need it? If you use homebridge-ui it made it for you

**Comment by fjhorrillo** [comment]
config.json: {"name":"AirzoneCloud","system":"https://www.airzonecloud.com","login":{"email":"mail@domain.com","password":"********************"},"debug":false,"user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15","platform":"AirzoneCloud"}
