### ISSUE TITLE
Temperature at OFF instead of system at STOP

### ISSUE THREAD

**Issue by vemeo** [fjhorrillo/homebridge-airzone-cloud#8]
I think there is an improvement to be made when we turn off all the zones.
Currently when we turn off the last zone with Homekit it switches the whole system to STOP. I think it would make more sense to just turn off the zone (as with the previous zones) and leave the system on its current state.
I think this would be easier and more flexible.
Advantage this would allow more flexibility between Homekit and thermostats. For example, if you wanted to go through the thermostat to turn a zone back on, you would simply press the On/Off button. At the moment as the system goes into STOP mode you have to change the mode (e.g. cold) after pressing on/off and choosing the temperature.

I am at your disposal if you want more explanations.

Stephen

**Comment by fjhorrillo** [comment]
Hello Stephen,

Thanks for your advice. I thought about this approach but the problem is that a [thermostat](https://developers.homebridge.io/#/service/Thermostat) has system mode and temperature but not on/off is for this reason that I chose the way to do it with the all zones mode.

Additionally, if I split it, a thermostat for each device and one for each zone I need a service with on/off and temperature and I don't know which one I can use. What service type you think is good for each zone?

Regards.

**Comment by vemeo** [comment]
Hi,

Thank you for your quick reply.
I am not sure I understand everything (I am not a specialist :-) )
However I noticed that there was a difference in treatment if we have several active zones or only one when we turn off the zone.

I give you an example.

Let's imagine that I have 2 zones ON (for example living room and bedroom). If I turn OFF the bedroom zone from Homekit => The physical thermostat of the bedroom switches OFF (also on the AirZone application) and the living room zone continues to work normally. As long as I don't turn off the living room zone from HomeKit I can turn ON the bedroom zone by pressing the ON/OFF button on the physical thermostat of the bedroom.
If I then turn OFF the living room zone (which is the last one running) the whole AirZone system goes to STOP mode (which was not the case when I turned OFF only the bedroom zone).
I think you understood but I prefer to explain it to you again in more detail.

I also looked at the link you sent me and apparently there is the possibility to set a thermostat to OFF via the Thermostat service.

![Uploading Capture d’écran 2021-07-06 à 16.56.51.png…]()


I must have missed something :-)

Regards.

**Comment by fjhorrillo** [comment]
Hello @vemeo,

I tried to add a device for the system and on it control the mode and use the current for the zone but HomeKit doesn't have the way to implement a thermostat only with on/off.

If you want, I could add an option in the config to disable the switch off automatically when all zones are off, and with this, the user could choose if use it or not.

Regards.

**Comment by vemeo** [comment]
Hi @fjhorrillo,

That would be great ! Thanks for taking my comment into account.

Regards

**Comment by BertoTavira** [comment]
+1 to this :)

Would be nice that instead of making system to change to STOP mode, it keeps the last mode used, like it happens when using the physical  controller

**Comment by fjhorrillo** [comment]
Done in v0.3.6. The default value for "auto off" is true, to avoid this behavior uncheck the Auto Off option under Advance configuration on the configuration.

**Comment by fjhorrillo** [comment]
Done in v0.3.6. The default value for "auto off" is true, to avoid this behavior uncheck the Auto Off option under Advance configuration on the configuration.
